### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by kihwankim** [LeeJiHyeong/spg#28]
Todo List
- [ ] file System code
- [ ] upload the img which for advertise

Finished List
- [x] make html my page
- [x] admin backend code for deleting board and user data
- [x] admin backend code for permitting user data 
- [x] add auth of pages in admin page
- [x] admin page css/js
- [x] admin page
- [x] add combining user data and password change frontend page and backend code
- [x] fix bug of changing header when I am authenticated
- [x] fix bug of role about cascade
- [x] change url from Management to management in UserController
- [x] change header of register page
- [x] change password page css
- [x] css html of my page

**Comment by LeeJiHyeong** [comment]
Additionally, Comment table & JPA code are required

**Comment by LeeJiHyeong** [comment]
+++ Also views number attribute in freeBoard table!!!

**Comment by happykwon94** [comment]
Resolved issues:
-  change password page css
-  change header of register page
-  change url from Management to management in UserController
-  password change frontend page and backend code

**Comment by kihwankim** [comment]
you just click the checkbox so if you did that please check the check box
